### ISSUE TITLE
CNN: Normalization before/after L-inf is applied?

### ISSUE THREAD

**Issue by ChristopherBrix** [verivital/vnn-comp#17]
I did not participate in the competition, but would like to use the CNN challenges to evaluate my own toolkit ([Debona](https://github.com/ChristopherBrix/Debona), based on [Neurify](https://github.com/tcwangshiqi-columbia/Neurify)). I've noticed that @FlorianJaeckle [stated](https://github.com/verivital/vnn-comp/issues/3#issuecomment-657775002) that the perturbation should be applied *after* the normalization (divide by 255, subtract mean, divide by variance). However, I can only reproduce the CIFAR10 results if I apply it *before*  the normalization (after dividing by 255).
nnenum (@stanleybak) seems to do the same, as the networks are modified to include the normalization, and [the perturbation is applied to the input](https://github.com/verivital/vnn-comp/blob/ef50ffebda6b356ba8e52bef82b9f93d9d2b45bd/2020/CNN/nnenum/nnenum/cnn/eth/eth_check.py#L65)

So is it safe to assume that the normalization should always be done last, for all 4 CNNs?

**Comment by stanleybak** [comment]
There were two benchmarks proposed for CNN networks, one from @GgnDpSngh called ETH in nnenum which you linked to (called ggn in the report), and the other was proposed by @FlorianJaeckle that we call OVAL in nnenum. The normalization is done differently for these two. See [here](https://github.com/verivital/vnn-comp/blob/ef50ffebda6b356ba8e52bef82b9f93d9d2b45bd/2020/CNN/nnenum/nnenum/cnn/oval/oval_check.py) for the oval file we were working on with nnenum, although I'm not even sure if that's correct since nnenum didn't have results for the oval benchmarks in time for the report. The OVAL benchmarks are pretty hard, and use a long timeout.

For making sure the normalization is done correctly, the strategy I used was to make sure the images classified as expected. For OVAL, all images should classify correctly if the normalization is performed correctly. Hope that helps clear things up.

**Comment by ChristopherBrix** [comment]
Great, thanks a lot! This makes sense now.
